[project]
name = "steely"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Max Seeliger", email = "maximilian.seeliger@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "torch>=2.6.0",
]

[project.scripts]
steely = "steely:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
